export const IPC = {
  SSH: {
    CONNECT: 'ssh:connect',
    DISCONNECT: 'ssh:disconnect',
    INPUT: 'ssh:input',
    OUTPUT: 'ssh:output',
    RESIZE: 'ssh:resize',
    CLOSE: 'ssh:close',
    ACCEPT_HOST_KEY: 'ssh:acceptHostKey',
    LIST_KNOWN_HOSTS: 'ssh:listKnownHosts',
    DELETE_KNOWN_HOST: 'ssh:deleteKnownHost',
  },
  SESSIONS: {
    LIST: 'sessions:list',
    SAVE: 'sessions:save',
    DELETE: 'sessions:delete',
    GET_FILE_PATH: 'sessions:getFilePath',
  },
  LOG: {
    SEND: 'log:send',
  },
  FOLDERS: {
    LIST: 'folders:list',
    SAVE: 'folders:save',
    DELETE: 'folders:delete',
  },
  CREDENTIALS: {
    LIST: 'credentials:list',
    SAVE: 'credentials:save',
    DELETE: 'credentials:delete',
  },
  AI: {
    SEND_MESSAGE: 'ai:sendMessage',
    STREAM_CHUNK: 'ai:streamChunk',
    STREAM_END: 'ai:streamEnd',
    STREAM_ERROR: 'ai:streamError',
  },
  SFTP: {
    LIST_DIR: 'sftp:listDir',
    REALPATH: 'sftp:realpath',
    STAT: 'sftp:stat',
    MKDIR: 'sftp:mkdir',
    RMDIR: 'sftp:rmdir',
    UNLINK: 'sftp:unlink',
    RENAME: 'sftp:rename',
    CHMOD: 'sftp:chmod',
    DOWNLOAD: 'sftp:download',
    UPLOAD: 'sftp:upload',
    TRANSFER_PROGRESS: 'sftp:transferProgress',
    EDIT_REMOTE: 'sftp:editRemote',
    EDIT_SAVE_ERROR: 'sftp:editSaveError',
  },
  LOCAL: {
    LIST_DIR: 'local:listDir',
    HOME_PATH: 'local:homePath',
    DRIVES: 'local:drives',
    OPEN_FILE: 'local:openFile',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
  },
  APP: {
    OPEN_LOG: 'app:openLog',
    SAVE_WINDOW_STATE: 'app:saveWindowState',
    GET_WINDOW_STATE: 'app:getWindowState',
    HAS_LOCK_PASSWORD: 'app:hasLockPassword',
    SET_LOCK_PASSWORD: 'app:setLockPassword',
    VERIFY_LOCK_PASSWORD: 'app:verifyLockPassword',
    EXPORT_SESSIONS: 'app:exportSessions',
    IMPORT_SESSIONS: 'app:importSessions',
    CONFIRM_CLOSE: 'app:confirmClose',
    CONFIRM_CLOSE_RESPONSE: 'app:confirmCloseResponse',
    MENU_OPEN_SETTINGS: 'app:menuOpenSettings',
    MENU_OPEN_ABOUT: 'app:menuOpenAbout',
  },
} as const
